[workspace]
[package]
name = "tariswap"
version = "0.1.0"
edition = "2021"

[dependencies]
tari_template_abi = { git = "https://github.com/tari-project/tari-dan" }
tari_template_lib = { git = "https://github.com/tari-project/tari-dan" }

[lib]
crate-type = ["cdylib", "lib"]
